### ISSUE TITLE
how can i use the scripts sir

### ISSUE THREAD

**Issue by Ourfuture145** [pythoninfosec/clickerbot#1]
I using termux sir

**Comment by pythoninfosec** [comment]
Hi ,
First you need to go this page https://selenium-python.readthedocs.io/installation.html 
install selenium and chromedriver check this page and follow step by step then you need to edit script base on your requirement 
Search and found this line after "http://www.yourclickaddress.com/" then change like that.
 chrome.get("LINK YOUR PAGE / TIKLANACAK ADRES")

And also you need to found which page you want to click you can check your page found correct xpath address link  then change it.
https://www.google.com/search?q=how+to+found+xpath&rlz=1C1AVFC_enTR834TR834&oq=how+to+found+xpath&aqs=chrome..69i57j69i65j69i60l3.4891j0j4&sourceid=chrome&ie=UTF-8

 chrome.find_element_by_xpath('//*[@id="btd"]').click()

after this finished you can use python clicker.py 

If you want to know more detail just let me know..
